services:
  db:
    image: postgres:12.13-alpine3.17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=TokyoJoe138!
    volumes:
      - db-dev-data:/var/lib/postregressql/data
    
volumes:
  db-dev-data:
    